HotCar/HotCar.WebUI.Frontend/Controllers/FindTripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoogleMapsApi.Entities.Directions.Response;
using HotCar.BLL;
using HotCar.BLL.Abstract;
using HotCar.Entities;
using HotCar.WebUI.Frontend.Code;
using HotCar.WebUI.Frontend.Models;

namespace HotCar.WebUI.Frontend.Controllers
{
    public class FindTripController : Controller
    {
        #region Private Fields

        private List<Trip> _trips;
        private ITripManager _tripManager;
        private ISecurityManager _securityManager;
        private IUsersManager _userManager;

        #endregion

        #region Constructors

        public FindTripController(ITripManager tripManager, ISecurityManager securityManager, IUsersManager userManager)
        {
            this._tripManager = tripManager;
            this._securityManager = securityManager;
            this._userManager = userManager;

        }

        #endregion

        #region Actions

        [HttpGet]
        public ActionResult Index()
        {
            return View("Index");
        }

        [HttpPost]
        public ActionResult Index(FindTripModel findTrip)
        {
            _trips = this._tripManager.GetPassengerAvailableTrips(findTrip.From, findTrip.To);
            this.Session[SessionKeys.TRIPS] = _trips;

            return this.Results();
        }

        [HttpPost]
        public ActionResult Results(int page = 0, FiltersModel filters = null)
        {
            const int PageSize = 4;

            this._trips = (List<Trip>) this.Session[SessionKeys.TRIPS];

            var data = new List<Trip>();
            if (this._trips != null)
            {
                data.AddRange(this._trips);
            }

            this.ViewBag.NoSeatsCount = data.Count(x => x.AvailablePlacesCount == 0);
            this.ViewBag.PhotoCount = data.Count(x => x.Driver.Photo.Photo != null);

            if (filters != null)
            {
                if (filters.Date != null)
                {
                    DateTime date = DateTime.ParseExact(filters.Date, "dd/MM/yyyy",
                        System.Globalization.CultureInfo.InvariantCulture);
                    data.RemoveAll(x => x.TripTime.Date != date.Date);
                }

                data.RemoveAll(x => (x.TripTime.Hour < filters.FromHour));
                data.RemoveAll(x => (x.TripTime.Hour > filters.ToHour));
                data.RemoveAll(x => (x.TripTime.Hour == filters.ToHour) && (x.TripTime.Minute > 0));

                if (filters.HideWithNoSeats == true)
                {
                    data.RemoveAll(x => x.AvailablePlacesCount == 0);
                }

                this.ViewBag.WithWithoutPhotoCount = data.Count;
                this.ViewBag.PhotoCount = data.Count(x => x.Driver.Photo.Photo != null);

                if (filters.HideWithNoPhoto == true)
                {
                    data.RemoveAll(x => x.Driver.Photo.Photo == null);
                }
                this.ViewBag.NoSeatsCount = data.Count(x => x.AvailablePlacesCount == 0);
            }
            data = data.OrderBy(x => x.TripTime).ToList();

            var count = data.Count;

            var data_to_show_count = (count - (page * PageSize) >= PageSize) ? PageSize : count - (page * PageSize);
            data = data.GetRange((page*PageSize), data_to_show_count);

            this.ViewBag.MaxPage = (count == 0) ? 0 : (count/PageSize) - ((count%PageSize) == 0 ? 1 : 0);

            this.ViewBag.Page = page;
            this.ViewBag.Data = data;
            this.ViewBag.Count = count;


            if (Request.IsAjaxRequest())
            {
                return PartialView("ResultsPartial", ViewBag.Data);
            }
            return View("Results");
        }

        [Authorize]
        [HttpGet]
        public ActionResult TripDetail(int id)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this._securityManager.GetName());
            userModel.Trips.Add(this._tripManager.GetTripById(id));
                
            return View("TripDetail", userModel);
        }

        #endregion
    }
}

HotCar/HotCar.WebUI.Frontend/Controllers/TripDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotCar.BLL.Abstract;
using HotCar.Entities;
using HotCar.WebUI.Frontend.Code.ControllerExtensions;
using HotCar.WebUI.Frontend.Models;
using Newtonsoft.Json;

namespace HotCar.WebUI.Frontend.Controllers
{
    public class TripDetailController : Controller
    {
        #region ApplyToTripStatusString

        private const string APPLY_ERROR_PLACES = "недоступна кількість місць. Оновіть сторінку та повторіть спробу ще раз";
        
        private const string APPLY_OWNER_ERROR = "Ви не можете бути пасажиром власної поїздки";

        private const string APPLY_AGE_ERROR =
            "особи, які не досягли 18-и річного віку, не можуть реєструватись на поїздку";

        private const string APPLY_SUCCESS = "ваша заявка прийнята; очікуйте підтвердження від водія";

        #endregion

        #region Fields

        private readonly ITripManager _tripManager;
        private readonly ISecurityManager _securityManager;
        private readonly IUsersManager _userManager;
        private readonly ICommentManager _commentManager;
        private readonly IApplManager _applManager;

        #endregion

        #region Constructor

        public TripDetailController(IUsersManager userManager, ITripManager tripManager, 
            ICommentManager commentManager, ISecurityManager securityManager, IApplManager applManager)
        {
            this._userManager = userManager;
            this._tripManager = tripManager;
            this._commentManager = commentManager;
            this._securityManager = securityManager;
            this._applManager = applManager;
        }

        #endregion

        #region Actions

        [Authorize]
        [HttpGet]
        public ActionResult GetTripInfo(int tripId)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this._securityManager.GetName());        
            userModel.Trips.Add(this._tripManager.GetTripById(tripId));

            var driver = this._userManager.GetUser(userModel.Trips[0].Driver.Login); 
            userModel.Trips[0].Driver.Rating = this._commentManager.GetDriverRating(driver.Id);
            foreach (var x in userModel.Trips)
            {
                _tripManager.ClearPassengersFromTrip(x, false);
            }

            return View("GetTripInfo", userModel);
        }

        public ActionResult DriverComments(string login)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(login);
            userModel.UserInfo.Rating = this._commentManager.GetDriverRating(userModel.UserInfo.Id);
            userModel.Comments = this._commentManager.GetDriverComments(userModel.UserInfo.Id);
                   
            return Json(new
            {                
                htmlContent = this.RenderPartialViewToString("Modal/CommentPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult PassengerComments(string login)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(login);
            userModel.UserInfo.Rating = this._commentManager.GetPassengerRating(userModel.UserInfo.Id);
            userModel.Comments = this._commentManager.GetPassengerComments(userModel.UserInfo.Id);
            
            return Json(new
            {
                htmlContent = this.RenderPartialViewToString("Modal/CommentPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult AddNewComment(int tripId, string commentText, string about, double rating)
        {
            var userName = this._securityManager.GetName();           
            if (!this._commentManager.CreateNewComment(tripId, commentText, about, userName, rating))
            {
                return this.PassengerComments(about);
            }
            else
            {
                return this.DriverComments(about);
            }
                        
        }

        [Authorize]
        [HttpPost]
        [Authorize]
        public ActionResult SignToTrip(int tripId, byte countReservedSeats, int cost)
        {
            Passenger passenger = new Passenger()
            {
                UserInfo = _userManager.GetUser(User.Identity.Name),
                TripId = tripId,
                CountReservedSeats = countReservedSeats,
                Cost = cost
            };

            Trip trip = _tripManager.GetTripById(tripId);

            string applMessage;
            bool success = ChackPassengerAppl(passenger, trip, out applMessage);
          
            if (success)
            {
                _applManager.SignToTrip(passenger);
            }

            return Json(new
            {
                success = success,
                applMessage = applMessage
            });
        }

        #endregion

        #region Helpers

        bool ChackPassengerAppl(Passenger p, Trip t, out string applMessage)
        {
            if (p.UserInfo.Age < 18)
            {
                applMessage = APPLY_AGE_ERROR;
                return false;
            }
            else if (User.Identity.Name == t.Driver.Login)
            {
                applMessage = APPLY_OWNER_ERROR;
                return false;
            }
            else if (p.CountReservedSeats > t.AvailablePlacesCount)
            {
                applMessage = APPLY_ERROR_PLACES;
                return false;
            }

            applMessage = APPLY_SUCCESS;
            return true;
        }

        #endregion
    }
}

HotCar/HotCar.WebUI.Frontend/Views/FindTrip/Index.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Знайти поїздку";
    Layout = "~/Views/Shared/_BasicLayout.cshtml";
}

@section Scripts{
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&language=uk"></script>
    @Scripts.Render("~/bundles/FindTrip/scripts")
}

<div id="main" role="main">
    <div id="main-content-header">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="title">
                        Пошук поїздки
                    </h1>
                </div>
            </div>
        </div>
    </div>

    <div id="main-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @using (Html.BeginForm("Index", "FindTrip", FormMethod.Post))
                    {
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input class="form-control validate" id="from-address" name="from" placeholder="Звідки" type="text">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input class="form-control validate" id="to-address" name="to" placeholder="Куди" type="text">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button type="submit" id="btnFind" class="btn btn-contrast">Знайти</button>
                        </div>
                    }
                </div>
                <div class="col-lg-12 mg-t" style="margin-top: 40px;">
                    <img class="img-responsive center-block" alt="Map" width="300" height="300"
                         src="~/Content/images/FindTrip/map.png" />
                </div>
                <div class="fade" id="scroll-to-top">
                    <i class="fa-icon-chevron-up"></i>
                </div>
            </div>
        </div>
    </div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/FindTrip/Results.cshtml
@using System.Collections.Generic
@using System.Web.Optimization
@{
    ViewBag.Title = "Результати";
    Layout = "~/Views/Shared/_BasicLayout.cshtml";
}

@section Scripts{
    @Scripts.Render("~/bundles/FindTrip/results")
}
@section Styles{
    @Styles.Render("~/Content/jednotka/FindTrip/css")
}

<div id="main" role="main">
    <div id="main-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-bordered mg-b">
                                <div class="panel-body" style="background-color: white;">
                                    <!--#eaedf2-->
                                    <div class="row" id="no_seats_filter">
                                        <div class="col-lg-12">
                                            <div class="checkbox">
                                                <label>
                                                    <input id="hide_no_seats" class="filter" type="checkbox" value="">
                                                    Сховати заповнені (<label id="no_seats_count">@ViewBag.NoSeatsCount</label>)
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="hr-half" style="border-color: lightgrey;">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <h3 class="no-mg-t">Дата</h3>
                                            <div class="btn-group">
                                                <input id="dp2" class="form-control filter" placeholder="ДД/ММ/РРРР" type="text">
                                                <span id="dataclear" class="fa-icon-remove-sign"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 mg-t">
                                            Час: <span id="from_hour">0</span>h - <span id="to_hour">24</span>h
                                            <div id="hour-slider-range" style="margin: 10px;"></div>
                                        </div>
                                    </div>
                                    <hr class="hr-half" style="border-color: lightgrey;">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <h3 class="no-mg-t">Фото</h3>
                                            <div class="radio">
                                                <label>
                                                    <input class="filter" id="withPhotoRadio" name="radio" type="radio" value="">
                                                    Тільки з фото (<label id="with_photo_count">@ViewBag.PhotoCount</label>)
                                                </label>
                                            </div>
                                            <div class="radio">
                                                <label>
                                                    <input class="filter" id="noPhotoRadio" name="radio" type="radio" value="" checked="true">
                                                    Всі (<label id="total_count">@ViewBag.Count</label>)
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="col-lg-12">

                        <div id="trip_infos">
                            @Html.Partial("ResultsPartial", (IEnumerable<HotCar.Entities.Trip>)@ViewBag.Data)
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="fade" id="scroll-to-top">
            <i class="fa-icon-chevron-up"></i>
        </div>
    </div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/FindTrip/ResultsPartial.cshtml
@using System
@model System.Collections.Generic.IEnumerable<HotCar.Entities.Trip>

<h2 class="no-mg-t">Знайдено: <span id="all_trips_count">@ViewBag.Count</span> поїздок</h2>

<input type="hidden" id="noSeatsNum" value="@ViewBag.NoSeatsCount" />
<input type="hidden" id="PhotoNum" value="@ViewBag.PhotoCount" />
<input type="hidden" id="TotalNum" value="@ViewBag.WithWithoutPhotoCount" />
<input type="hidden" id="currPage" value="@ViewBag.Page" />

@foreach (var TripInfo in Model)
{
    <div class='panel trip-info' id="@TripInfo.Id">
        <div class='panel-body'>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-6 col-xs-3">
                        @if (TripInfo.Driver.Photo.Photo == null)
                        {
                            <div class='icon icon-wrap icon-circle icon-lg' style="background-color: #eaedf2; width: 100px; height: 100px;">
                                <div style="position: relative; top: 50%; transform: translateY(-50%);">
                                    <i class='fa-icon-user contrast'></i>
                                </div>
                            </div>
                        }
                        else
                        {
                            <img alt="@TripInfo.Driver.FirstName" width="100" height="100" class="img-circle img-responsive" src="@TripInfo.Driver.PhotoFormatted" />
                        }
                    </div>
                    <div class="col-md-6">
                        <p>@TripInfo.Driver.FirstName @TripInfo.Driver.SurName[0].</p>
                        @if (TripInfo.Driver.Birthday != null) { 
                            <p>вік: @TripInfo.Driver.Age</p>
                        }
                        @*<div style="font-size: 11px; margin-top: 30px;">
                            <i class="fa-icon-star text-contrast"></i>
                            <span>
                                немає відгуків
                            </span>
                        </div>*@
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-8">
                        <h4>@TripInfo.TripTime.ToShortDateString() - @TripInfo.TripTime.ToShortTimeString()</h4>
                        <div style="font-size: 13px; padding-top: 10px;">
                            <i class="fa-icon-circle-blank text-contrast"></i> @TripInfo.LocationAddresses[0] <br />
                            <i class="fa-icon-circle-blank text-contrast"></i> @TripInfo.LocationAddresses[@TripInfo.LocationAddresses.Count - 1]
                        </div>
                    </div>
                    <div class="col-md-4">
                        <h1 class="no-mg-t no-mg-b">@Decimal.ToInt32(TripInfo.CostOneSeat) ₴</h1>
                        <p>з пасажира</p>

                        @if (TripInfo.AvailablePlacesCount == 0)
                        {
                            <div class="mg-t"><h3>Заповнений</h3></div>
                        }
                        else
                        {
                            <div class="mg-t" style="font-size: 13px;">
                                <p>
                                    <span style="font-size: 20px;"> @TripInfo.AvailablePlacesCount </span>
                                    @if (TripInfo.AvailablePlacesCount == 1)
                                    {
                                        @:місце
                                                            }
                                    else if (TripInfo.AvailablePlacesCount <= 4)
                                    {
                                        @:місця
                                    }
                                    else
                                    {
                                        @:місць
                                    }
                                    залишилося
                                </p>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class='text-right'>
    <ul class='pagination'>

        @if (@ViewBag.Page > 0)
        {
            <li id="prev_page">
                <a href=''>
                    <i class='fa-icon-angle-left'></i>
                </a>
            </li>
        }

        @if (@ViewBag.MaxPage > 0)
        {
            for (var i = 1; i <= @ViewBag.MaxPage + 1; ++i)
            {
                if (@ViewBag.Page == (i - 1))
                {
                    <li class="active">
                        <a href=''>@i</a>
                    </li>
                }
                else
                {
                    <li>
                        <a href=''>@i</a>
                    </li>
                }
            }
        }

        @if (@ViewBag.Page < @ViewBag.MaxPage)
        {
            <li id="next_page">

                <a href=''>
                    <i class='fa-icon-angle-right'></i>
                </a>

            </li>
        }

    </ul>
</div>

HotCar/HotCar.WebUI.Frontend/Views/FindTrip/SignToTripModal.cshtml
@using System.Data.SqlTypes
@using System.Web.Optimization
@model HotCar.Entities.Trip
@{
    ViewBag.Title = "Підписка на поїздку";
    ViewBag.ModalId = "SignToTripModal";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}


<input type="hidden" id="costOneSeat" value="@System.Math.Truncate(Model.CostOneSeat)">

<div class="commentBox">
	<div id="workingContent" class="text-center">
		<img src="~/Content/images/UserAccount/loading.gif" id="status-image">
		<br/>
		<span id="working-text">йде обробка запиту...</span>
	</div>	
	<div id="applContent">
		<div class="count-places-text no-mg-t no-mg-b">Хочу зарезервувати (місць):</div>
		<br/>
		<div id="select-count-places" class="col-sm-12">
			<div class="col-sm-2">
				<select class="form-control" id="count-places" onchange=" selectChange() ">
					@for (byte i = 1; i < Model.AvailablePlacesCount + 1; i++)
					{
						<option class="bolder">@i</option>
					}
				</select>
			</div>
			&nbsp;
			&nbsp;
			<span id="count-places-view">
				<span class="fa-icon-user" id="count-places-image"></span>
			</span>
		</div>
		<br/>
		<hr class="hr-dashed hr-half"/>
		<div class="center money">
			<div class="input-group center money-group">
				<span class="input-group-addon count-places-text">Пропоную</span>
				<input class="form-control input-lg text-right" id="input-money" type="text" value="@System.Math.Truncate(Model.CostOneSeat)" onkeyup="this.value = this.value.replace (/\D/gi, '').replace (/^0+/, '')">
				<span class="input-group-addon">
					<h3 class="no-mg-t no-mg-b">₴ (грн)</h3>
				</span>
			</div>
		</div>
		<hr class="hr-dashed hr-half"/>
		<div class="btn btn-success" id="btn-assign" onclick='signToTrip("@Model.Id")'>Підписатись</div>
		<br/>
	</div>
	<br/>
</div>