HotCar/HotCar.WebUI.Frontend/Controllers/TripDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotCar.BLL.Abstract;
using HotCar.Entities;
using HotCar.WebUI.Frontend.Code.ControllerExtensions;
using HotCar.WebUI.Frontend.Models;
using Newtonsoft.Json;

namespace HotCar.WebUI.Frontend.Controllers
{
    public class TripDetailController : Controller
    {
        #region ApplyToTripStatusString

        private const string APPLY_ERROR_PLACES = "недоступна кількість місць. Оновіть сторінку та повторіть спробу ще раз";
        
        private const string APPLY_OWNER_ERROR = "Ви не можете бути пасажиром власної поїздки";

        private const string APPLY_AGE_ERROR =
            "особи, які не досягли 18-и річного віку, не можуть реєструватись на поїздку";

        private const string APPLY_SUCCESS = "ваша заявка прийнята; очікуйте підтвердження від водія";

        #endregion

        #region Fields

        private readonly ITripManager _tripManager;
        private readonly ISecurityManager _securityManager;
        private readonly IUsersManager _userManager;
        private readonly ICommentManager _commentManager;
        private readonly IApplManager _applManager;

        #endregion

        #region Constructor

        public TripDetailController(IUsersManager userManager, ITripManager tripManager, 
            ICommentManager commentManager, ISecurityManager securityManager, IApplManager applManager)
        {
            this._userManager = userManager;
            this._tripManager = tripManager;
            this._commentManager = commentManager;
            this._securityManager = securityManager;
            this._applManager = applManager;
        }

        #endregion

        #region Actions

        [Authorize]
        [HttpGet]
        public ActionResult GetTripInfo(int tripId)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this._securityManager.GetName());        
            userModel.Trips.Add(this._tripManager.GetTripById(tripId));

            var driver = this._userManager.GetUser(userModel.Trips[0].Driver.Login); 
            userModel.Trips[0].Driver.Rating = this._commentManager.GetDriverRating(driver.Id);
            foreach (var x in userModel.Trips)
            {
                _tripManager.ClearPassengersFromTrip(x, false);
            }

            return View("GetTripInfo", userModel);
        }

        public ActionResult DriverComments(string login)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(login);
            userModel.UserInfo.Rating = this._commentManager.GetDriverRating(userModel.UserInfo.Id);
            userModel.Comments = this._commentManager.GetDriverComments(userModel.UserInfo.Id);
                   
            return Json(new
            {                
                htmlContent = this.RenderPartialViewToString("Modal/CommentPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult PassengerComments(string login)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(login);
            userModel.UserInfo.Rating = this._commentManager.GetPassengerRating(userModel.UserInfo.Id);
            userModel.Comments = this._commentManager.GetPassengerComments(userModel.UserInfo.Id);
            
            return Json(new
            {
                htmlContent = this.RenderPartialViewToString("Modal/CommentPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult AddNewComment(int tripId, string commentText, string about, double rating)
        {
            var userName = this._securityManager.GetName();           
            if (!this._commentManager.CreateNewComment(tripId, commentText, about, userName, rating))
            {
                return this.PassengerComments(about);
            }
            else
            {
                return this.DriverComments(about);
            }
                        
        }

        [Authorize]
        [HttpPost]
        [Authorize]
        public ActionResult SignToTrip(int tripId, byte countReservedSeats, int cost)
        {
            Passenger passenger = new Passenger()
            {
                UserInfo = _userManager.GetUser(User.Identity.Name),
                TripId = tripId,
                CountReservedSeats = countReservedSeats,
                Cost = cost
            };

            Trip trip = _tripManager.GetTripById(tripId);

            string applMessage;
            bool success = ChackPassengerAppl(passenger, trip, out applMessage);
          
            if (success)
            {
                _applManager.SignToTrip(passenger);
            }

            return Json(new
            {
                success = success,
                applMessage = applMessage
            });
        }

        #endregion

        #region Helpers

        bool ChackPassengerAppl(Passenger p, Trip t, out string applMessage)
        {
            if (p.UserInfo.Age < 18)
            {
                applMessage = APPLY_AGE_ERROR;
                return false;
            }
            else if (User.Identity.Name == t.Driver.Login)
            {
                applMessage = APPLY_OWNER_ERROR;
                return false;
            }
            else if (p.CountReservedSeats > t.AvailablePlacesCount)
            {
                applMessage = APPLY_ERROR_PLACES;
                return false;
            }

            applMessage = APPLY_SUCCESS;
            return true;
        }

        #endregion
    }
}

HotCar/HotCar.WebUI.Frontend/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Configuration.Internal;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Helpers;
using System.Web.Mvc;
using HotCar.BLL.Abstract;
using HotCar.BLL.Services;
using HotCar.Entities;
using HotCar.WebUI.Frontend.Code;
using HotCar.WebUI.Frontend.Code.ControllerExtensions;
using HotCar.WebUI.Frontend.Models;


namespace HotCar.WebUI.Frontend.Controllers
{
    public class UserAccountController : Controller
    {
        #region ApplyPassengerStatusStringConst

        private const string APPLY_PLACES_ERROR = "немає стільки вільних місць";

        private const string APPLY_DRIVER_ERROR = "тільки водій на поїздці може підтвердити заявку на цю поїздку";

        private const string APPLY_SUCCESS = "пасажир успішно доданий";

        private const string APPLY_PASSENGER_ERROR = "такий пасажир не є учасником поїздки";

        private const string APPLY_UNEXPECTED_ERROR = "невідома помилка; будь ласка зверніться до адміністрації сайту";

        private const string APPLY_SUCCESS_INFO = "Ваша заявка підтверджена! водій: ";

        private const string APPLY_SUCCESS_SUBJECT = "[підтвердження заявки]";

        #endregion

        #region Fields

        private readonly ITripManager _tripManager;
        private readonly IUsersManager _userManager;
        private readonly ICommentManager _commentManager;
        private readonly IApplManager _applManager;
        private readonly ISecurityManager _securityManager;
        private readonly ISmsService _smsService;
        private readonly IEmailService _emailService;

        #region Avatar Settings

        private const int AvatarStoredWidth = 100;  // ToDo - Change the size of the stored avatar image
        private const int AvatarStoredHeight = 100; // ToDo - Change the size of the stored avatar image
        private const int AvatarScreenWidth = 400;  // ToDo - Change the value of the width of the image on the screen

        private static string TempFolder = WebConfigurationManager.AppSettings["TempFolderPath"];
        private static string MapTempFolder = "~" + TempFolder;     

        private readonly string[] _imageFileExtensions = { ".jpg", ".png", ".gif", ".jpeg" };

        #endregion

        #endregion

        #region Constructor

        public UserAccountController(IUsersManager userManager, ITripManager tripManager,
            ICommentManager commentManager, IApplManager applManager,
            ISecurityManager securityManager, ISmsService smsService, IEmailService emailService)
        {
            this._userManager = userManager;
            this._tripManager = tripManager;
            this._commentManager = commentManager;
            this._applManager = applManager;
            this._securityManager = securityManager;
            this._smsService = smsService;
            this._emailService = emailService;
        }

        #endregion
        
        #region Web Actions

        [Authorize]
        public ActionResult Index()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);

            return View(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetOutDatedTrips()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = this._tripManager.GetOutDatedUserTrips(User.Identity.Name, true);

            return this.GetHtmlTripContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetActiveTrips()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = this._tripManager.GetActiveUserTrips(User.Identity.Name, true);

            return this.GetHtmlTripContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetMyComments()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this._securityManager.GetName());
            userModel.Comments = this._commentManager.GetAllMyComments(userModel.UserInfo.Id);

            return this.GetHtmlCommentsContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetCommentsAboutMe()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);
            userModel.Comments = this._commentManager.GetAllAboutMeComments(userModel.UserInfo.Id);

            return this.GetHtmlCommentsContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetNewApplsToTrip()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = _tripManager.GetActiveTripsForDriverByLogin(User.Identity.Name);

            int countNewAppls = 0;
            for (int i = 0; i < userModel.Trips.Count; i++)
            {
                _tripManager.ClearPassengersFromTrip(userModel.Trips[i], true);

                if (userModel.Trips[i].Passangers.Count == 0)
                {
                    userModel.Trips.RemoveAt(i--);
                    continue;
                }

                countNewAppls += userModel.Trips[i].Passangers.Count;
            }
            
            return Json(new
            {
                count = countNewAppls,
                htmlContent = this.RenderPartialViewToString("Partials/ApplPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ApplyPassengerToTrip(int tripId, string passengerLogin)
        {
            Trip currentTrip = _tripManager.GetTripById(tripId);

            Passenger pass = _applManager.GetUnConfirmedPassengerToTrip(tripId).FirstOrDefault(
                p => String.Compare(p.UserInfo.Login, passengerLogin, true) == 0);

            string message;
            bool success = ChackPassengerToTrip(currentTrip, pass, out message);

            if (success)
            {
                if (!_applManager.ConfirmApplsForUser(pass))
                {
                    message = APPLY_UNEXPECTED_ERROR;
                    success = false;
                }
                else
                {
                    try
                    {
                        string name = currentTrip.Driver.FirstName + " " + currentTrip.Driver.SurName;
                        InformPassengerForApplying(pass.UserInfo.Mail, pass.UserInfo.Phone,
                        APPLY_SUCCESS_INFO + currentTrip.Driver.Phone + "(" + name + ")", 
                        APPLY_SUCCESS_SUBJECT);
                    }
                    catch (Exception)
                    {
                    }
                }
            }

            return Json(new
            {
                success, 
                message = message
            });
        }

        #region Avatar Actions

        [ValidateAntiForgeryToken]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null || !files.Any()) return Json(new { success = false, errorMessage = "No file uploaded." });
            var file = files.FirstOrDefault();  // get ONE only
            if (file == null || !IsImage(file)) return Json(new { success = false, errorMessage = "File is of wrong format." });
            if (file.ContentLength <= 0) return Json(new { success = false, errorMessage = "File cannot be zero length." });
            var webPath = GetTempSavedFilePath(file);
            return Json(new { success = true, fileName = webPath.Replace("/", "\\") }); // success
        }

        [HttpPost]
        public ActionResult Save(string t, string l, string h, string w, string fileName)
        {
            try
            {
                // Calculate dimensions
                var top = Convert.ToInt32(t.Replace("-", "").Replace("px", ""));
                var left = Convert.ToInt32(l.Replace("-", "").Replace("px", ""));
                var height = Convert.ToInt32(h.Replace("-", "").Replace("px", ""));
                var width = Convert.ToInt32(w.Replace("-", "").Replace("px", ""));

                // Get file from temporary folder
                var fn = Path.Combine(Server.MapPath(MapTempFolder), Path.GetFileName(fileName));
                // ...get image and resize it, ...
                var img = new WebImage(fn);
                img.Resize(width, height);
                // ... crop the part the user selected, ...
                img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);
                // ... delete the temporary file,...         
                System.IO.File.Delete(fn);
                // ... and save the new one.                          
                bool res = this._userManager.UploadPhoto(img.GetBytes(), img.ImageFormat);
           
                return Json(new { success = res});
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = "Unable to upload file.\nERRORINFO: " + ex.Message });
            }
        }

        #endregion

        #region Setting Actions

        [Authorize]
        public ActionResult ChangeFirstName(String firstName)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);
            userModel.UserInfo.FirstName = firstName;
            bool updated = this._userManager.UpdateUserInfo(userModel.UserInfo);


HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Partials/ApplPartial.cshtml
@using System
@model HotCar.WebUI.Frontend.Models.UserModel


@foreach(var trip in Model.Trips)
{
	<div class="row text-box text-box-title-above text-box-big-image">
		<div class="col-sm-12">
			<hr class="text-contrast"/>
			<div class="col-sm-5 animation">
				<div class="appl">
					<hr class="hr-half">
					<span class="title">
					<a href="@Url.Action("GetTripInfo", "TripDetail", new {tripId = trip.Id})">@trip.LocationAddresses[0] - @trip.LocationAddresses[@trip.LocationAddresses.Count - 1]</a>
				</span>
					<br/>
					<br/>
					<span class="cost-block">
					<i class="fa-icon-usd text-contrast"></i>
					<span> Ціна (</span>
					<span class="cost text-contrast">@trip.CostOneSeat.ToString("0.##")</span>
					<span> ) </span>
					<span> грн</span>
				</span>
					<span class="trip-time-block">
					<i class="fa-icon-time text-contrast"></i>
					<span>@trip.TripTime.Hour.ToString("D2"):@trip.TripTime.Minute.ToString("D2")</span>
				</span>
					<span class="trip-date-block">
					<i class="fa-icon-calendar text-contrast"></i>
					<span>@trip.TripTime.ToString("d")</span>
				</span>
					<br/>
					<span>
					<i class="fa-icon-group text-contrast"></i>
					<span>Вільних місць: ( </span>
					<span class="available-places-count text-contrast">@trip.AvailablePlacesCount</span>
					<span> ) </span>
				</span>
					<a class="btn btn-link link-contrast btn-sm trip-more" href="@Url.Action("GetTripInfo", "TripDetail", new {tripId = trip.Id})">
						<i class="fa-icon-truck"></i>
						<span>Детальніше</span>
					</a>
					<div class="row">
						<div class="col-sm-12">
							<a href="@Url.Action("GetTripInfo", "TripDetail", new {tripId = trip.Id})">
								<img class="img-responsive center-block img-rounded-half" alt="Cras tempus ligula a tempor adipiscing" maxwidth="842" maxheight="364" src="~/Content/images/UserAccount/tripRoadNew.jpg">
							</a>
						</div>
					</div>
					<span>
						<i class="fa-icon-user"></i>
						<span>@trip.Driver.Login.ToLower()</span>
					</span>
				</div>
			</div>
			<div class="col-lg-7 mg-t">
				<div class="panel panel-bordered">
					<div class="panel-heading text-center">
						<label style="font-size: 18px;">заявки</label>
					</div>
					<div class="panel-body">
						<div class="row">
							<div>
								@foreach (var pass in trip.Passangers)
								{
									<div class="col-md-3 portfolio-boxes">
										<div class="portfolio-box">
											<a class='image-link' data-lightbox='team' href="@Url.Action("UserPhoto", "Account", new { login = @pass.UserInfo.Login })">
												<i class="fa-icon-search"></i>
                                                <img class="img-responsive img-rounded center-block" alt="Etiam vestibulum" width="262" height="262" src="@Url.Action("UserPhoto", "Account", new {login = @pass.UserInfo.Login})">
											</a>
											<div>
												<span>@pass.UserInfo.FirstName</span> <span> @pass.UserInfo.Age </span> <span> р.</span>
											</div>
											<div>
												<i class="fa-icon-usd text-contrast"></i>
												<span> пропонує</span>
												<br/>
												<span>( </span>
												<span class="text-contrast">@pass.Cost</span>
												<span> ) грн за</span>
											</div>
											<div>
												<i class="fa-icon-group text-contrast"></i>
												<span>( </span>
												<span class="text-contrast">@pass.CountReservedSeats</span>
												@if (pass.CountReservedSeats == 1)
												{
													<span> ) місце</span>
												}
												else
												{
													<span> ) місця</span>
												}
												<br/>
											</div>
											<div>
												<div class="btn btn-contrast btn-bordered btn-sm btn_apply" onclick=' applyApplToTrip("@trip.Id", "@pass.UserInfo.Login") '>підтвердити</div>
											</div>
										</div>
									</div>
								}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Partials/CommentPartial.cshtml
@using System
@model HotCar.WebUI.Frontend.Models.UserModel

<div class="row">
	<div class="col-sm-12">
		@foreach (var comment in @Model.Comments)
		{
			<div class="media animation-comments">
				<div class="pull-left">
				    <div class="media-object">
                        <img width ="60" height="60" src="@Url.Action("UserPhoto", "Account", new { login = comment.UserInfo.Login})" />
				    </div>
				</div>
				<div class="media-body">
					<div class="content">
						<div class="toolbar">
							<h4 class="title text-contrast"></h4>
							<i class="fa-icon-user text-contrast"></i>
							<span>@comment.UserInfo.FirstName @comment.UserInfo.SurName</span>
                            <a class="btn btn-link link-contrast btn-sm" href="@Url.Action("GetTripInfo","TripDetail", new{ tripId = comment.TripId})">
                                <i class="fa-icon-truck"></i>
                                <span>подорож</span>
                            </a>
						</div>
						<p>@comment.Text</p>
						<p>
							<i class="fa-icon-calendar text-contrast"></i>
							<span> @comment.Time </span>
						</p>
					</div>
				</div>
			</div>
		}
	</div>
	<br/>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Partials/TripPartial.cshtml
@using System
@model HotCar.WebUI.Frontend.Models.UserModel

@foreach (HotCar.Entities.Trip trip in @Model.Trips)
{
	<div class="col-sm-6 animation">
	<div class="trip">
		<hr class="hr-half">
		<span class="title">
			<a href="@Url.Action("GetTripInfo", "TripDetail", new {tripId = trip.Id})">@trip.LocationAddresses[0] - @trip.LocationAddresses[@trip.LocationAddresses.Count - 1]</a>
		</span>
		<br/>
		<br/>
		<span class="cost-block">
			<i class="fa-icon-usd text-contrast"></i>
			<span> Ціна (</span>
			<span class="cost text-contrast">@trip.CostOneSeat.ToString("0.##")</span>
			<span> ) </span>
			<span> грн</span>
		</span>
		<span class="trip-time-block">
			<i class="fa-icon-time text-contrast"></i>
			<span>@trip.TripTime.Hour.ToString("D2"):@trip.TripTime.Minute.ToString("D2")</span>
		</span>
		<span class="trip-date-block">
			<i class="fa-icon-calendar text-contrast"></i>
			<span>@trip.TripTime.ToString("d")</span>
		</span>
		<br/>
		<span>
			<i class="fa-icon-group text-contrast"></i>
			<span>Вільних місць: ( </span>
			<span class="available-places-count text-contrast">@trip.AvailablePlacesCount</span>
			<span> ) </span>
		</span>
		<a class="btn btn-link link-contrast btn-sm trip-more" href="@Url.Action("GetTripInfo", "TripDetail", new {tripId = trip.Id})">
			<i class="fa-icon-truck"></i>
			<span>Детальніше</span>
		</a>
		<div class="row">
			<div class="col-sm-12">
				<a href="@Url.Action("GetTripInfo", "TripDetail", new {tripId = trip.Id})">
					<img class="img-responsive center-block img-rounded-half" alt="Cras tempus ligula a tempor adipiscing" maxwidth="842" maxheight="364" src="~/Content/images/UserAccount/tripRoadNew.jpg">
				</a>
			</div>
		</div>
		<span >
			<i class="fa-icon-user"></i>
			<span>@trip.Driver.Login.ToLower()</span>
		</span>
	</div>
	</div>
}