HotCar/HotCar.WebUI.Frontend/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Configuration.Internal;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Helpers;
using System.Web.Mvc;
using HotCar.BLL.Abstract;
using HotCar.BLL.Services;
using HotCar.Entities;
using HotCar.WebUI.Frontend.Code;
using HotCar.WebUI.Frontend.Code.ControllerExtensions;
using HotCar.WebUI.Frontend.Models;


namespace HotCar.WebUI.Frontend.Controllers
{
    public class UserAccountController : Controller
    {
        #region ApplyPassengerStatusStringConst

        private const string APPLY_PLACES_ERROR = "немає стільки вільних місць";

        private const string APPLY_DRIVER_ERROR = "тільки водій на поїздці може підтвердити заявку на цю поїздку";

        private const string APPLY_SUCCESS = "пасажир успішно доданий";

        private const string APPLY_PASSENGER_ERROR = "такий пасажир не є учасником поїздки";

        private const string APPLY_UNEXPECTED_ERROR = "невідома помилка; будь ласка зверніться до адміністрації сайту";

        private const string APPLY_SUCCESS_INFO = "Ваша заявка підтверджена! водій: ";

        private const string APPLY_SUCCESS_SUBJECT = "[підтвердження заявки]";

        #endregion

        #region Fields

        private readonly ITripManager _tripManager;
        private readonly IUsersManager _userManager;
        private readonly ICommentManager _commentManager;
        private readonly IApplManager _applManager;
        private readonly ISecurityManager _securityManager;
        private readonly ISmsService _smsService;
        private readonly IEmailService _emailService;

        #region Avatar Settings

        private const int AvatarStoredWidth = 100;  // ToDo - Change the size of the stored avatar image
        private const int AvatarStoredHeight = 100; // ToDo - Change the size of the stored avatar image
        private const int AvatarScreenWidth = 400;  // ToDo - Change the value of the width of the image on the screen

        private static string TempFolder = WebConfigurationManager.AppSettings["TempFolderPath"];
        private static string MapTempFolder = "~" + TempFolder;     

        private readonly string[] _imageFileExtensions = { ".jpg", ".png", ".gif", ".jpeg" };

        #endregion

        #endregion

        #region Constructor

        public UserAccountController(IUsersManager userManager, ITripManager tripManager,
            ICommentManager commentManager, IApplManager applManager,
            ISecurityManager securityManager, ISmsService smsService, IEmailService emailService)
        {
            this._userManager = userManager;
            this._tripManager = tripManager;
            this._commentManager = commentManager;
            this._applManager = applManager;
            this._securityManager = securityManager;
            this._smsService = smsService;
            this._emailService = emailService;
        }

        #endregion
        
        #region Web Actions

        [Authorize]
        public ActionResult Index()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);

            return View(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetOutDatedTrips()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = this._tripManager.GetOutDatedUserTrips(User.Identity.Name, true);

            return this.GetHtmlTripContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetActiveTrips()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = this._tripManager.GetActiveUserTrips(User.Identity.Name, true);

            return this.GetHtmlTripContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetMyComments()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this._securityManager.GetName());
            userModel.Comments = this._commentManager.GetAllMyComments(userModel.UserInfo.Id);

            return this.GetHtmlCommentsContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetCommentsAboutMe()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);
            userModel.Comments = this._commentManager.GetAllAboutMeComments(userModel.UserInfo.Id);

            return this.GetHtmlCommentsContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetNewApplsToTrip()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = _tripManager.GetActiveTripsForDriverByLogin(User.Identity.Name);

            int countNewAppls = 0;
            for (int i = 0; i < userModel.Trips.Count; i++)
            {
                _tripManager.ClearPassengersFromTrip(userModel.Trips[i], true);

                if (userModel.Trips[i].Passangers.Count == 0)
                {
                    userModel.Trips.RemoveAt(i--);
                    continue;
                }

                countNewAppls += userModel.Trips[i].Passangers.Count;
            }
            
            return Json(new
            {
                count = countNewAppls,
                htmlContent = this.RenderPartialViewToString("Partials/ApplPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ApplyPassengerToTrip(int tripId, string passengerLogin)
        {
            Trip currentTrip = _tripManager.GetTripById(tripId);

            Passenger pass = _applManager.GetUnConfirmedPassengerToTrip(tripId).FirstOrDefault(
                p => String.Compare(p.UserInfo.Login, passengerLogin, true) == 0);

            string message;
            bool success = ChackPassengerToTrip(currentTrip, pass, out message);

            if (success)
            {
                if (!_applManager.ConfirmApplsForUser(pass))
                {
                    message = APPLY_UNEXPECTED_ERROR;
                    success = false;
                }
                else
                {
                    try
                    {
                        string name = currentTrip.Driver.FirstName + " " + currentTrip.Driver.SurName;
                        InformPassengerForApplying(pass.UserInfo.Mail, pass.UserInfo.Phone,
                        APPLY_SUCCESS_INFO + currentTrip.Driver.Phone + "(" + name + ")", 
                        APPLY_SUCCESS_SUBJECT);
                    }
                    catch (Exception)
                    {
                    }
                }
            }

            return Json(new
            {
                success, 
                message = message
            });
        }

        #region Avatar Actions

        [ValidateAntiForgeryToken]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null || !files.Any()) return Json(new { success = false, errorMessage = "No file uploaded." });
            var file = files.FirstOrDefault();  // get ONE only
            if (file == null || !IsImage(file)) return Json(new { success = false, errorMessage = "File is of wrong format." });
            if (file.ContentLength <= 0) return Json(new { success = false, errorMessage = "File cannot be zero length." });
            var webPath = GetTempSavedFilePath(file);
            return Json(new { success = true, fileName = webPath.Replace("/", "\\") }); // success
        }

        [HttpPost]
        public ActionResult Save(string t, string l, string h, string w, string fileName)
        {
            try
            {
                // Calculate dimensions
                var top = Convert.ToInt32(t.Replace("-", "").Replace("px", ""));
                var left = Convert.ToInt32(l.Replace("-", "").Replace("px", ""));
                var height = Convert.ToInt32(h.Replace("-", "").Replace("px", ""));
                var width = Convert.ToInt32(w.Replace("-", "").Replace("px", ""));

                // Get file from temporary folder
                var fn = Path.Combine(Server.MapPath(MapTempFolder), Path.GetFileName(fileName));
                // ...get image and resize it, ...
                var img = new WebImage(fn);
                img.Resize(width, height);
                // ... crop the part the user selected, ...
                img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);
                // ... delete the temporary file,...         
                System.IO.File.Delete(fn);
                // ... and save the new one.                          
                bool res = this._userManager.UploadPhoto(img.GetBytes(), img.ImageFormat);
           
                return Json(new { success = res});
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = "Unable to upload file.\nERRORINFO: " + ex.Message });
            }
        }

        #endregion

        #region Setting Actions

        [Authorize]
        public ActionResult ChangeFirstName(String firstName)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);
            userModel.UserInfo.FirstName = firstName;
            bool updated = this._userManager.UpdateUserInfo(userModel.UserInfo);


HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/AboutMeSettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "AboutMeSettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-icon">
				<i class="fa-icon-comment-alt"></i>
			</div>
			<div class="panel-body">
				<h3 class="panel-title">Про мене</h3>
				<textarea id="aboutSpan" class="form-control" readonly="readonly" style="background-color: white; border: none; resize: none; text-align: center;" >@Model.UserInfo.AboutMe</textarea>
				<br/>
				<br/>
				<p class="text-contrast">Розкажіть про себе:</p>
				<br/>
				<div class="form-group control-group">
                    <textarea class="form-control" data-rule-required="true" id="contact_message" name="contact[message]" placeholder="розкажіть..." style="resize: none; text-align: center"></textarea>
				</div>
				<br/>
				<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changeAbout();">Розповісти</button>
			</div>
		</div>
	</div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/AvatarUpload.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Upload";
    ViewBag.ModalId = "AvatarUpload";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<section id="avatar-upload-box">
    @using (Ajax.BeginForm("Upload", "UserAccount",
        new AjaxOptions() { HttpMethod = "POST" },
        new { enctype = "multipart/form-data", id = "avatar-upload-form" }))
    {
        @Html.AntiForgeryToken()
        <input type="file" name="files" /><br>
        <div class="upload-file-notice">Maximum Size: <span id="avatar-max-size"></span> MB</div>
    }
    <div class="upload-progress col-md-6 hidden">
        <div class="upload-percent-value pull-left">0%</div>
        <div class="upload-percent-bar pull-left"></div>
    </div>
    <div id="upload-status"></div>
</section>
<section id="avatar-crop-box" class="hidden">
    <p>
        <img src="" id="crop-avatar-target" alt="Uploaded image" />
        <div id="preview-pane">
            <div class="preview-container">
                <img src="" class="jcrop-preview" alt="Preview" />
            </div>
        </div>
    </p>
    <p><button class="btn btn-default" onclick=" saveAvatar() ">Save Avatar</button></p>
</section>
<div id="avatar-result" class="hidden">
    <img src="" alt="Final Image"/>
    <span>Аватарку змінено</span>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/BirthdaySettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "BirthdaySettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-icon">
				<i class="fa-icon-calendar"></i>
			</div>
			<div class="panel-body">
			    <h3 class="panel-title">
			        <span id="birthdaySpan">
                        @Model.UserInfo.Birthday.Value.ToString("d")
                    </span>
			    </h3>
				<p class="text-contrast">Змінити дату народження:</p>
				<br/>
				<div class="form-group control-group">
				    <input class="form-control" data-rule-required="true" id="contact_birthday" name="contact[name]" placeholder="DD.MM.YYYY" type="text">
                </div>
				<br/>
				<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changeBirthday();">змінити</button>
			</div>
		</div>
	</div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/FirstNameSettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "FirstNameSettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-icon">
				<i class="fa-icon-certificate"></i>
			</div>
			<div class="panel-body">
			    <h3 class="panel-title">
                    <span id="firstNameSpan">
                        @Model.UserInfo.FirstName
                    </span>
			    </h3>
				<p class="text-contrast">Нове ім'я:</p>
				<br/>
				<div class="form-group control-group">
                    <input class="form-control" data-rule-required="true" id="contact_name" name="contact[name]" placeholder="Ім'я" type="text">
                    <label id="contact_name_error" class="hidden">Невірне ім'я</label>
				</div>
				<br/>
				<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changeFirstName();">Змінити</button>
			</div>
		</div>
	</div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/MailSettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "MailSettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-body">
				<div class="panel-icon">
				<i class="fa-icon-envelope-alt"></i>
			</div>
			    <h3 class="panel-title">
			        <span id="mailSpan">
                        @Model.UserInfo.Mail
                    </span>
			    </h3>
			<p class="text-contrast">Нова електронна пошта: </p>
			<br/>
			<div class="form-group control-group">
			    <input class="form-control" data-rule-email="true" data-rule-required="true" id="contact_email" name="contact[email]" placeholder="E-Mail" type="text">
                <label id="contact_email_error" class="hidden">Невірна електронна пошта</label>
			</div>
			<br/>
			<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changeMail();">Змінити</button>
			</div>
		</div>
	</div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/PasswordSettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "PasswordSettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-icon">
				<i class="fa-icon-user"></i>
			</div>
			<div class="panel-body">
				<h3 class="panel-title">Змінити пароль</h3>				
                <p class="text-contrast">Змінити на:</p>
				<br/>
			    <div class="form-group control-group">
			        <input class="form-control" id="input-passwordOld" placeholder="старий пароль" type="password">
                    <br/>
			        <input class="form-control" id="input-passwordNew" placeholder="новий пароль" type="password">
                    <br />
			        <input class="form-control" id="input-passwordNewConfirm" placeholder="новий пароль (підтвердження)" type="password">
                    <label id="contact_password_error" class="hidden">Пароль надто короткий або надто довгий (6 - 20 символів)</label>
			    </div>
				<br/>
				<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changePassword();">змінити</button>
			</div>
		</div>
		
	</div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/PhoneSettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "PhoneSettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-icon">
				<i class="fa-icon-phone"></i>
			</div>
			<div class="panel-body">
			    <h3 class="panel-title">
			        <span id="phoneSpan">
                        @Model.UserInfo.Phone
                    </span>
			    </h3>
				<p class="text-contrast">Новий телефон: </p>
				<br/>
				<div class="form-group control-group">
					<input class="form-control" data-rule-required="true" id="contact_phone" name="contact[name]" placeholder="телефон" type="text">
                    <label id="contact_phone_error" class="hidden">Невірний телефон -> +XXXXXXXXXXXX</label>
				</div>
				<br/>
				<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changePhone();">Змінити</button>
			</div>
		</div>
	</div>
</div>

HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Modals/SettingsModal/SurNameSettings.cshtml
@model HotCar.WebUI.Frontend.Models.UserModel
@{
    ViewBag.Title = "Налаштування";
    ViewBag.ModalId = "SurNameSettings";
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
}

<div class="detailBox">
	<div class="panel-item">
		<div class="panel panel-big">
			<div class="panel-icon">
				<i class="fa-icon-certificate"></i>
			</div>
			<div class="panel-body">
			    <h3 class="panel-title">
			        <span id="surNameSpan">
                        @Model.UserInfo.SurName
                    </span>
			    </h3>
				<p class="text-contrast">Нове прізвище:</p>
				<br/>
				<div class="form-group control-group">
					<input class="form-control" data-rule-required="true" id="contact_surname" name="contact[name]" placeholder="Прізвище" type="text">
                    <label id="contact_surname_error" class="hidden">Невірне прізвище</label>
				</div>
				<br/>
				<button class="btn btn-contrast btn-bordered col-sm-4" onclick="changeSurName();">Змінити</button>
			</div>
		</div>
	</div>
</div>