HotCar/HotCar.WebUI.Frontend/Controllers/LayoutController.cs
using HotCar.BLL.Abstract;
using HotCar.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotCar.WebUI.Frontend.Controllers
{
    public class LayoutController : Controller
    {
        #region Private Fields

        private ISecurityManager _securityManager;
        private IUsersManager _userManager;

        #endregion

        #region Constructors

        public LayoutController(ISecurityManager securityManager, IUsersManager userManager)
        {
            this._securityManager = securityManager;
            this._userManager = userManager;
        }

        #endregion

        #region Web Actions

        public ActionResult UserPhoto()
        {
            string login = this._securityManager.GetName();
            UserPhoto userPhoto = this._userManager.GetUserPhoto(login);
            if (userPhoto.Photo != null)
            {
                return this.File(userPhoto.Photo, MimeMapping.GetMimeMapping(userPhoto.FileExtension));
            }
            else
            {
                string fileName = Server.MapPath("~/Content/images/no-user-photo.png");
                return this.File(fileName, MimeMapping.GetMimeMapping(fileName));
            }

        }

        [HttpPost]
        public ActionResult GetUserPhoto()
        {
            string login = this.User.Identity.Name; // ToDo: use SecurityManager for this purpose
            UserPhoto userPhoto = this._userManager.GetUserPhoto(login);

            string file = @"data:image/"+userPhoto.FileExtension+";base64," + Convert.ToBase64String(userPhoto.Photo);
            return Json(new { file = file}); // success                                 
        }

        #endregion
    }
}

HotCar/HotCar.WebUI.Frontend/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Configuration.Internal;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Helpers;
using System.Web.Mvc;
using HotCar.BLL.Abstract;
using HotCar.BLL.Services;
using HotCar.Entities;
using HotCar.WebUI.Frontend.Code;
using HotCar.WebUI.Frontend.Code.ControllerExtensions;
using HotCar.WebUI.Frontend.Models;


namespace HotCar.WebUI.Frontend.Controllers
{
    public class UserAccountController : Controller
    {
        #region ApplyPassengerStatusStringConst

        private const string APPLY_PLACES_ERROR = "немає стільки вільних місць";

        private const string APPLY_DRIVER_ERROR = "тільки водій на поїздці може підтвердити заявку на цю поїздку";

        private const string APPLY_SUCCESS = "пасажир успішно доданий";

        private const string APPLY_PASSENGER_ERROR = "такий пасажир не є учасником поїздки";

        private const string APPLY_UNEXPECTED_ERROR = "невідома помилка; будь ласка зверніться до адміністрації сайту";

        private const string APPLY_SUCCESS_INFO = "Ваша заявка підтверджена! водій: ";

        private const string APPLY_SUCCESS_SUBJECT = "[підтвердження заявки]";

        #endregion

        #region Fields

        private readonly ITripManager _tripManager;
        private readonly IUsersManager _userManager;
        private readonly ICommentManager _commentManager;
        private readonly IApplManager _applManager;
        private readonly ISecurityManager _securityManager;
        private readonly ISmsService _smsService;
        private readonly IEmailService _emailService;

        #region Avatar Settings

        private const int AvatarStoredWidth = 100;  // ToDo - Change the size of the stored avatar image
        private const int AvatarStoredHeight = 100; // ToDo - Change the size of the stored avatar image
        private const int AvatarScreenWidth = 400;  // ToDo - Change the value of the width of the image on the screen

        private static string TempFolder = WebConfigurationManager.AppSettings["TempFolderPath"];
        private static string MapTempFolder = "~" + TempFolder;     

        private readonly string[] _imageFileExtensions = { ".jpg", ".png", ".gif", ".jpeg" };

        #endregion

        #endregion

        #region Constructor

        public UserAccountController(IUsersManager userManager, ITripManager tripManager,
            ICommentManager commentManager, IApplManager applManager,
            ISecurityManager securityManager, ISmsService smsService, IEmailService emailService)
        {
            this._userManager = userManager;
            this._tripManager = tripManager;
            this._commentManager = commentManager;
            this._applManager = applManager;
            this._securityManager = securityManager;
            this._smsService = smsService;
            this._emailService = emailService;
        }

        #endregion
        
        #region Web Actions

        [Authorize]
        public ActionResult Index()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);

            return View(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetOutDatedTrips()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = this._tripManager.GetOutDatedUserTrips(User.Identity.Name, true);

            return this.GetHtmlTripContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetActiveTrips()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = this._tripManager.GetActiveUserTrips(User.Identity.Name, true);

            return this.GetHtmlTripContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetMyComments()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this._securityManager.GetName());
            userModel.Comments = this._commentManager.GetAllMyComments(userModel.UserInfo.Id);

            return this.GetHtmlCommentsContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetCommentsAboutMe()
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);
            userModel.Comments = this._commentManager.GetAllAboutMeComments(userModel.UserInfo.Id);

            return this.GetHtmlCommentsContent(userModel);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetNewApplsToTrip()
        {
            UserModel userModel = new UserModel();
            userModel.Trips = _tripManager.GetActiveTripsForDriverByLogin(User.Identity.Name);

            int countNewAppls = 0;
            for (int i = 0; i < userModel.Trips.Count; i++)
            {
                _tripManager.ClearPassengersFromTrip(userModel.Trips[i], true);

                if (userModel.Trips[i].Passangers.Count == 0)
                {
                    userModel.Trips.RemoveAt(i--);
                    continue;
                }

                countNewAppls += userModel.Trips[i].Passangers.Count;
            }
            
            return Json(new
            {
                count = countNewAppls,
                htmlContent = this.RenderPartialViewToString("Partials/ApplPartial", userModel)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ApplyPassengerToTrip(int tripId, string passengerLogin)
        {
            Trip currentTrip = _tripManager.GetTripById(tripId);

            Passenger pass = _applManager.GetUnConfirmedPassengerToTrip(tripId).FirstOrDefault(
                p => String.Compare(p.UserInfo.Login, passengerLogin, true) == 0);

            string message;
            bool success = ChackPassengerToTrip(currentTrip, pass, out message);

            if (success)
            {
                if (!_applManager.ConfirmApplsForUser(pass))
                {
                    message = APPLY_UNEXPECTED_ERROR;
                    success = false;
                }
                else
                {
                    try
                    {
                        string name = currentTrip.Driver.FirstName + " " + currentTrip.Driver.SurName;
                        InformPassengerForApplying(pass.UserInfo.Mail, pass.UserInfo.Phone,
                        APPLY_SUCCESS_INFO + currentTrip.Driver.Phone + "(" + name + ")", 
                        APPLY_SUCCESS_SUBJECT);
                    }
                    catch (Exception)
                    {
                    }
                }
            }

            return Json(new
            {
                success, 
                message = message
            });
        }

        #region Avatar Actions

        [ValidateAntiForgeryToken]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null || !files.Any()) return Json(new { success = false, errorMessage = "No file uploaded." });
            var file = files.FirstOrDefault();  // get ONE only
            if (file == null || !IsImage(file)) return Json(new { success = false, errorMessage = "File is of wrong format." });
            if (file.ContentLength <= 0) return Json(new { success = false, errorMessage = "File cannot be zero length." });
            var webPath = GetTempSavedFilePath(file);
            return Json(new { success = true, fileName = webPath.Replace("/", "\\") }); // success
        }

        [HttpPost]
        public ActionResult Save(string t, string l, string h, string w, string fileName)
        {
            try
            {
                // Calculate dimensions
                var top = Convert.ToInt32(t.Replace("-", "").Replace("px", ""));
                var left = Convert.ToInt32(l.Replace("-", "").Replace("px", ""));
                var height = Convert.ToInt32(h.Replace("-", "").Replace("px", ""));
                var width = Convert.ToInt32(w.Replace("-", "").Replace("px", ""));

                // Get file from temporary folder
                var fn = Path.Combine(Server.MapPath(MapTempFolder), Path.GetFileName(fileName));
                // ...get image and resize it, ...
                var img = new WebImage(fn);
                img.Resize(width, height);
                // ... crop the part the user selected, ...
                img.Crop(top, left, img.Height - top - AvatarStoredHeight, img.Width - left - AvatarStoredWidth);
                // ... delete the temporary file,...         
                System.IO.File.Delete(fn);
                // ... and save the new one.                          
                bool res = this._userManager.UploadPhoto(img.GetBytes(), img.ImageFormat);
           
                return Json(new { success = res});
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = "Unable to upload file.\nERRORINFO: " + ex.Message });
            }
        }

        #endregion

        #region Setting Actions

        [Authorize]
        public ActionResult ChangeFirstName(String firstName)
        {
            UserModel userModel = new UserModel();
            userModel.UserInfo = this._userManager.GetUser(this.User.Identity.Name);
            userModel.UserInfo.FirstName = firstName;
            bool updated = this._userManager.UpdateUserInfo(userModel.UserInfo);


HotCar/HotCar.WebUI.Frontend/Views/UserAccount/Index.cshtml
@using System.Web.Optimization

@model HotCar.WebUI.Frontend.Models.UserModel

@{
    ViewBag.Title = "Кабінет";
    Layout = "~/Views/Shared/_BasicLayout.cshtml";
}

@section Scripts{
    @Scripts.Render("~/bundles/UserAccount/scripts")
    @Scripts.Render("~/bundles/UserAccount/Avatar/scripts")
}

@section Styles{
    @Styles.Render("~/Content/jednotka/UserAccount/css")
    @Styles.Render("~/Content/jednotka/UserAccount/Avatar/css")

}

<link href="~/Content/jednotka/UserAccount/menu-styles.css" rel="stylesheet" />


@Html.Partial("Modals/SettingsModal/PasswordSettings", @Model)
@Html.Partial("Modals/SettingsModal/MailSettings", @Model)
@Html.Partial("Modals/SettingsModal/FirstNameSettings", @Model)
@Html.Partial("Modals/SettingsModal/SurNameSettings", @Model)
@Html.Partial("Modals/SettingsModal/PhoneSettings", @Model)
@Html.Partial("Modals/SettingsModal/BirthdaySettings", @Model)
@Html.Partial("Modals/SettingsModal/AboutMeSettings", @Model)
@Html.Partial("Modals/SettingsModal/AvatarUpload")
@Html.Partial("Modals/ApplyApplModal")
<!--short main information for user-->
<div class="short-user-info">
    <div class="menu-line">
        <hr class="hr-half">
    </div>
    <div class="col-sm-12">
        <div class="short-info col-sm-2">
            <div class="short-info-top">
                <i class="fa-icon-group fa-icon-fixed-width short-info-picture"></i>
                <span class="short-info-bracket">(</span>
                <span id="count-new-appls" class="short-info-count">
					<img id="newappls-loading" src="~/Content/images/UserAccount/loading-white.gif" width="26" height="26">
				</span>
                <span class="short-info-bracket">)</span>
            </div>
            <div class="short-info-bottom"> нові заявки </div>
        </div>
        <div class="short-info col-sm-2">
            <div class="short-info-top">
                <i class="fa-icon-comments-alt fa-icon-fixed-width short-info-picture"></i>
                <span class="short-info-bracket">(</span>
                <span id="count-users-comments" class="short-info-count">
					<img id="users-comments-loading" src="~/Content/images/UserAccount/loading-white.gif" width="26" height="26">
				</span>
                <span class="short-info-bracket">)</span>
            </div>
            <div class="short-info-bottom">коментарів</div>
        </div>
        <div class="short-info col-sm-2">
            <div class="short-info-top">
                <i class="fa-icon-suitcase fa-icon-fixed-width short-info-picture"></i>
                <span class="short-info-bracket">(</span>
                <span id="count-actual-trips" class="short-info-count">
					<img id="actual-trips-loading" src="~/Content/images/UserAccount/loading-white.gif" width="26" height="26">
				</span>
                <span class="short-info-bracket">)</span>
            </div>
            <div class="short-info-bottom">актуальні поїздки</div>
        </div>
        <div class="short-info col-sm-2">
            <div class="short-info-top">
                <i class="fa-icon-ok fa-icon-fixed-width short-info-picture"></i>
                <span class="short-info-bracket">(</span>
                <span id="count-outdated-trips" class="short-info-count">
					<img id="outdated-trips-loading" src="~/Content/images/UserAccount/loading-white.gif" width="26" height="26">
				</span>
                <span class="short-info-bracket">)</span>
            </div>
            <div class="short-info-bottom">минулі поїздки</div>
        </div>
        <div class="col-sm-4">
            <div class="col-sm-12 center">
                <i class="fa-icon-unlock-alt fa-icon-fixed-width user-account-picture"></i>
                <span class="user-name" id="indexTopFirstSurNameSpan">@Model.UserInfo.FirstName @Model.UserInfo.SurName</span>
            </div>
            <br/>
            <br/>
            <div class="col-sm-12 center">
                <i class="fa-icon-user fa-icon-fixed-width user-account-picture"></i>
                <span class="user-name">@Model.UserInfo.Login</span>
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div class="menu-line">
        <hr class="hr-half">
    </div>
    <div class="col-sm-12">
        <div class="col-sm-4 user-bottom-info">
            <i class="fa-icon-envelope-alt fa-icon-fixed-width user-account-picture"></i>
            <span id="indexTopMailSpan">@Model.UserInfo.Mail</span>
        </div>
        <div class="col-sm-4 user-bottom-info">
            <i class="fa-icon-phone fa-icon-fixed-width user-account-picture"></i>
            <span id="indexTopPhoneSpan">@Model.UserInfo.Phone</span>
        </div>
        <div class="col-sm-3 user-bottom-info">
            <i class="fa-icon-calendar fa-icon-fixed-width user-account-picture"></i>
            <span id="indexTopBirthdaySpan">@Model.UserInfo.Birthday.Value.ToString("d")</span>
        </div>
    </div>
</div>
<div class="short-user-info photo-content">
    <div сlass="row panels">
        <div class="col-sm-12">
            <div class="menu-line">
                <hr/>
            </div>
        </div>
    </div>
</div>
<!--end short main information for user-->

<div class="all-content">
<div class="user-page-content">
<!--menu-->
<div class="style-switcher">
	<div class="style-switcher-heading">
		<i class="fa-icon-wrench settings-menu" id="settings-menu"></i>
	</div>
</div>
<div class="style-switcher">
	<div class="style-switcher-heading">
		<i class="fa-icon-group appl-menu" id="appl-menu"></i>
	</div>
</div>
<div class="style-switcher">
	<div class="style-switcher-heading">
		<i class="fa-icon-truck trips-menu" id="trips-menu"></i>
	</div>
</div>
<div class="style-switcher">
	<div class="style-switcher-heading">
		<i class="fa-icon-comments comments-menu" id="comments-menu"></i>
	</div>
</div>
<!--end menu-->
<!--settings content-->
<hr class="text-contrast"/>
<div class="current-active-menu">
	<i class="fa-icon-wrench text-contrast fa-icon-fixed-width current-menu-active-picture"></i>
	<span>Налаштування</span>
</div>
<div class="settings-content hide-content" id="settings-content">
	<br/>
	<div class="container">
		<div class="row panels">
			<div class="col-sm-3 "></div>
			<div class='profile-boxes col-sm-3 '>
				<div class='profile-box'>
					<div id="avatar-upload">
						<a class='image-link'>
							<i class='fa-icon-refresh'></i>
							<img alt="avatar" width="262" height="262" id="user-avatar" class="img-circle img-responsive" src="@Url.Action("UserPhoto", "Layout")"/>
						</a>
					</div>
				</div>
			</div>
		</div>
		<br/>
		<div class="row panels">
			<div class="col-sm-3 panel-item" id="name-settings">
				<a class="panel panel-big">
					<div class="panel-icon">
						<i class="fa-icon-certificate"></i>
					</div>
					<div class="panel-body">
						<h3 class="panel-title">Ім'я</h3>
						<p>
							<span id="indexFirstNameSpan">
                                @Model.UserInfo.FirstName
                            </span>
						</p>
					</div>
				</a>
			</div>
			<div class="col-sm-3 panel-item" id="sur-name-settings">
				<a class="panel panel-big">
					<div class="panel-icon">
						<i class="fa-icon-cog"></i>
					</div>
					<div class="panel-body">
						<h3 class="panel-title">Прізвище</h3>
						<p>
							<span id="indexSurNameSpan">
                                @Model.UserInfo.SurName
                            </span>
						</p>
					</div>
				</a>
			</div>
			<div class="col-sm-3 panel-item" id="birthday-settings">
				<a class="panel panel-big">
					<div class="panel-icon">
						<i class="fa-icon-calendar"></i>
					</div>
					<div class="panel-body">
						<h3 class="panel-title">День народження</h3>
						<p>
							<span id="indexBirthdaySpan">
                                @Model.UserInfo.Birthday.Value.ToString("d")
                            </span>
						</p>
					</div>
				</a>
			</div>
		</div>
		<br/>
		<br/>
		<div class="row panels">
			<div class="col-sm-3 panel-item" id="password-settings">
				<a class="panel panel-big">
					<div class="panel-icon">
						<i class="fa-icon-user"></i>
					</div>
					<div class="panel-body">
						<h3 class="panel-title">Пароль</h3>
						<p>**********</p>
					</div>
				</a>
			</div>
			<div class="col-sm-3 panel-item" id="mail-settings">
				<a class="panel panel-big">
					<div class="panel-icon">
						<i class="fa-icon-envelope-alt"></i>
					</div>
					<div class="panel-body">
						<h3 class="panel-title">Електронна пошта</h3>
						<p>
							<span id="indexMailSpan">
                                @Model.UserInfo.Mail
                            </span>
						</p>
					</div>
				</a>
			</div>
			<div class="col-sm-3 panel-item" id="phone-settings">
				<a class="panel panel-big">
					<div class="panel-icon">
						<i class="fa-icon-phone"></i>
					</div>
					<div class="panel-body">
						<h3 class="panel-title">Телефон</h3>
						<p>
							<span id="indexPhoneSpan">
                                @Model.UserInfo.Phone
                            </span>
						</p>
					</div>
				</a>
			</div>
		</div>
		<br/>
		<br/>
		<div class="row panels">
			<div class="row panels">
				<div class="col-sm-9 panel-item" id="about-me-settings">
					<div class="panel panel-big">
						<div class="panel-icon">
							<i class="fa-icon-comment-alt"></i>
						</div>
						<div class="panel-body">
							<h3 class="panel-title">Про мене</h3>
                            <textarea id="indexAboutSpan" class="form-control" readonly="readonly" style="background-color: white; border: none; text-align: center; resize: none;">@Model.UserInfo.AboutMe</textarea>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br/>
	</div>
</div>
<!--end settings content-->
<!--comments content-->
<hr class="text-contrast"/>
<div class="current-active-menu">
	<i class="fa-icon-comments-alt text-contrast fa-icon-fixed-width current-menu-active-picture"></i>
	<span>Коментарі</span>
</div>
<div class="hide-content" id="comments-content">
	<hr class="text-contrast"/>
	<ul class="nav nav-tabs tabs">
		<li class="active" id="tab-my-comments">
			<a data-toggle="tab">
				<i class="fa-icon-mail-reply text-contrast"></i>
				Мої
				<span> (</span>
				<span id="tab-count-my-comments"></span>
				<span> )</span>
			</a>
		</li>
		<li id="tab-comments-about-me">
			<a data-toggle="tab">
				<i class="fa-icon-share-alt text-contrast"></i>
				Про мене
				<span> (</span>
				<span id="tab-count-comments-about-me"></span>
				<span> )</span>
			</a>
		</li>
	</ul>
	<br/>
	<br/>
	<div id="comments-region"></div>
</div>
<!--end comments content-->
<!--trips content-->
<hr class="text-contrast"/>
<div class="current-active-menu">
	<i class="fa-icon-truck text-contrast fa-icon-fixed-width current-menu-active-picture"></i>
	<span>Поїздки</span>
</div>
<div class="hide-content" id="trips-content">
	<hr class="text-contrast"/>
	<div class="row text-box text-box-title-above text-box-big-image">
		<ul class="nav nav-tabs tabs">
			<li class="active" id="tab-actual-trips">
				<a data-toggle="tab">
					<i class="fa-icon-suitcase text-contrast"></i>
					Актуальні
					<span> (</span>
					<span id="tab-count-actual-trips"></span>
					<span> )</span>
				</a>
			</li>
			<li id="tab-outdated-trips">
				<a data-toggle="tab">
					<i class="fa-icon-ok text-contrast"></i>
					Минулі
					<span> (</span>
					<span id="tab-count-oudated-trips"></span>
					<span> )</span>
				</a>
			</li>
		</ul>
		<div id="trips-region" class="col-sm-10"></div>
	</div>
</div>
<br/>
<hr class="hr-half">
<!--end trip content-->
<!--application to trips-->
<br/>
<div class="current-active-menu ">
	<i class="fa-icon-group text-contrast fa-icon-fixed-width current-menu-active-picture"></i>
	<span>Нові заявки</span>
</div>
<div class="hide-content" id="appl-content"></div>
<br/>
<hr class="hr-half">
<!--application to trips-->
</div>
<div class="fade" id='scroll-to-top'>
    <i class='fa-icon-chevron-up'></i>
</div>
<br/>
</div>